# Site settings
title: David Mohundro
email: david@mohundro.com
description: > # this means to ignore newlines until "baseurl:"
  David Mohundro is a programmer, speaker, dad, gamer, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mohundro.com" # the base hostname & protocol for your site
twitter_username: drmohundro
github_username:  drmohundro
highlighter: pygments

# Build settings
markdown: kramdown
