title: David Mohundro - Programmer, Speaker, Dad, Gamer, and more
email: david@mohundro.com
description: David Mohundro is a programmer, speaker, dad, gamer, and more.

baseurl: ""
url: "https://mohundro.com"

twitter:
  username: drmohundro

twitter_username: drmohundro
github_username: drmohundro
google_analytics_tracking_id: UA-3973340-1

paginate: 10
paginate_path: "/blog/page:num/"
permalink: pretty

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
